name: Full-Stack CI Pipeline (Node.js & Frontend)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  # =======================================
  # Backend CI
  # =======================================
  build_and_test_backend:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Backend Dependencies
        run: npm install

      - name: Run Backend Tests
        run: npm test

      - name: Build (Optional)
        run: npm run build || true

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-backend-dist
          path: |
            package.json
            server.js
            src/

  # =======================================
  # Frontend CI
  # =======================================
  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-frontend
          path: |
            index.html
            css/
            js/

  # =======================================
  # Deployment Stage (after CI passes)
  # =======================================
  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_test_backend, build_frontend]

    steps:
      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: node-backend-dist
          path: backend-app

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: static-frontend
          path: frontend-app

      - name: Deployment Placeholder
        run: |
          echo "--- Deployment Started ---"
          echo "Backend ready in backend-app/"
          echo "Frontend ready in frontend-app/"
          echo "Add real deployment script here..."
          echo "--- Deployment Finished ---"
